defaults: &defaults

development:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV['RAILS_TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['RAILS_TWITTER_CONSUMER_SECRET'] %>

test:
  <<: *defaults

production:
  <<: *defaults
