defaults: &defaults

development:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV['RAILS_TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['RAILS_TWITTER_CONSUMER_SECRET'] %>
  facebook:
    key: <%= ENV['RAILS_FACEBOOK_KEY'] %>
    secret: <%= ENV['RAILS_FACEBOOK_SECRET'] %>
  slack:
    client_id: <%= ENV['RAILS_SLACK_CLIENT_ID'] %>
    client_secret: <%= ENV['RAILS_SLACK_CLIENT_SECRET'] %>

test:
  <<: *defaults

production:
  <<: *defaults
  twitter:
    consumer_key: <%= ENV['RAILS_TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['RAILS_TWITTER_CONSUMER_SECRET'] %>
  facebook:
    key: <%= ENV['RAILS_FACEBOOK_KEY'] %>
    secret: <%= ENV['RAILS_FACEBOOK_SECRET'] %>
  slack:
    client_id: "<%= ENV['RAILS_SLACK_CLIENT_ID'] %>"
    client_secret: <%= ENV['RAILS_SLACK_CLIENT_SECRET'] %>
